# Generated by Django 2.2.5 on 2019-11-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile/None/avater.png', upload_to='profile/%Y/%m/%d/'),
        ),
    ]
