# Generated by Django 2.2.5 on 2019-10-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('old', 'Old'), ('uncompleted', 'Uncompleted'), ('renovated', 'Renovated')], max_length=25, null=True)),
                ('property_price', models.DecimalField(decimal_places=0, max_digits=30)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('property_area', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('building_age', models.CharField(blank=True, choices=[('05', '0-5 Years'), ('10', '0-10 Years'), ('15', '0-15 Years'), ('20', '0-20 Years'), ('21', '20+ Years')], max_length=25, null=True)),
                ('rent_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=25, null=True)),
                ('property_room', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'More than 5')], max_length=25, null=True)),
                ('bedroom', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'More than 5')], max_length=25, null=True)),
                ('bathroom', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'More than 5')], max_length=25, null=True)),
                ('lot_size', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('plan_image', models.ImageField(blank=True, default='profile/None/no-img.jpg', null=True, upload_to='plans_images/')),
                ('church', models.BooleanField(blank=True, default=False, null=True)),
                ('school', models.BooleanField(blank=True, default=False, null=True)),
                ('mosque', models.BooleanField(blank=True, default=False, null=True)),
                ('market', models.BooleanField(blank=True, default=False, null=True)),
                ('hospital', models.BooleanField(blank=True, default=False, null=True)),
                ('resturant', models.BooleanField(blank=True, default=False, null=True)),
                ('beach', models.BooleanField(blank=True, default=False, null=True)),
                ('air_conditioning', models.BooleanField(blank=True, default=False, null=True)),
                ('parking', models.BooleanField(blank=True, default=False, null=True)),
                ('sewer', models.BooleanField(blank=True, default=False, null=True)),
                ('water', models.BooleanField(blank=True, default=False, null=True)),
                ('lawn', models.BooleanField(blank=True, default=False, null=True)),
                ('swimming_pool', models.BooleanField(blank=True, default=False, null=True)),
                ('barbecue', models.BooleanField(blank=True, default=False, null=True)),
                ('tv_cable', models.BooleanField(blank=True, default=False, null=True)),
                ('microwave', models.BooleanField(blank=True, default=False, null=True)),
                ('wi_fi', models.BooleanField(blank=True, default=False, null=True)),
                ('gym', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.State')),
            ],
        ),
        migrations.CreateModel(
            name='AdsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(default='profile/None/no-img.jpg', upload_to='ads/')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.Ads')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.Category'),
        ),
        migrations.AddField(
            model_name='ads',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.Lga'),
        ),
        migrations.AddField(
            model_name='ads',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='ads',
            name='property_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.Offer'),
        ),
        migrations.AddField(
            model_name='ads',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.State'),
        ),
    ]
