# Generated by Django 2.2.5 on 2019-11-04 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0002_auto_20191020_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
