# Generated by Django 2.2.5 on 2019-10-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='hospital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='market',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='resturant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
