# Generated by Django 2.2.5 on 2020-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_ads_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='plan_image',
            field=models.ImageField(blank=True, default='profile/None/no_image.png', null=True, upload_to='plans_images/'),
        ),
        migrations.AlterField(
            model_name='adsimages',
            name='ad_image',
            field=models.ImageField(blank=True, default='profile/None/no_image.png', null=True, upload_to='ads/'),
        ),
    ]
