# Generated by Django 2.2.5 on 2019-10-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20191009_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='lga',
            new_name='city',
        ),
    ]
