# Generated by Django 2.2.5 on 2019-10-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_auto_20191010_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='ad_area',
            new_name='property_area',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='ad_price',
            new_name='property_price',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='ad_title',
            new_name='property_title',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='ad_offer',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='ad_room',
        ),
        migrations.AddField(
            model_name='ads',
            name='property_offer',
            field=models.ManyToManyField(blank=True, null=True, to='advert.Offer'),
        ),
        migrations.AddField(
            model_name='ads',
            name='property_room',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'More than 5')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'More than 5')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='bedroom',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'More than 5')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='building_age',
            field=models.CharField(blank=True, choices=[('05', '0-5 Years'), ('10', '0-10 Years'), ('15', '0-15 Years'), ('20', '0-20 Years'), ('21', '20+ Years')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=25, null=True),
        ),
    ]
