# Generated by Django 2.2.5 on 2019-10-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191027_0346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
