# Generated by Django 2.2.5 on 2019-10-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
